#!/usr/bin/env node
/**
 * Build the nutrition data the game ships from the verified SKU map.
 *
 * Two outputs, from one source of truth (`docs/ENERVIT_SKU_MAP.json`):
 *
 *  1. `public/art/enervit/<id>.webp` — the packshot, downscaled from the
 *     brand-asset library. The originals are print artwork: 193 PNGs totalling
 *     808 MB. Shipping any of them raw would blow the 15 MB initial-load budget
 *     on its own, so they are resized to a UI-sized card and re-encoded.
 *
 *  2. `src/data/enervit.ts` — a typed, trimmed copy of the SKU records. The
 *     source JSON is 43 kB, most of it provenance notes that are essential to
 *     the document and useless to the runtime.
 *
 * Deliberately a build step rather than a runtime import: the packshot library
 * lives outside the repository (it is the client's brand asset store, not ours
 * to vendor), so this cannot run in CI and its outputs are committed. Re-run it
 * when the SKU map changes.
 *
 * Usage: node tools/nutrition/build.mjs [--check]
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');
const SRC = resolve(ROOT, 'docs/ENERVIT_SKU_MAP.json');
const OUT_ART = resolve(ROOT, 'public/art/enervit');
const OUT_TS = resolve(ROOT, 'src/data/enervit.ts');

/** Card height in CSS pixels × 2 for retina. Packshots are portrait-ish. */
const PACKSHOT_H = 260;

const CHECK = process.argv.includes('--check');

const map = JSON.parse(readFileSync(SRC, 'utf8'));
mkdirSync(OUT_ART, { recursive: true });

const records = [];
let written = 0;
let missing = 0;

for (const s of map.skus) {
  const art = `art/enervit/${s.id}.webp`;
  const dest = resolve(ROOT, 'public', art);
  const hasSource = s.packshotPath && existsSync(s.packshotPath);

  if (!hasSource) {
    missing++;
    console.warn(`! ${s.id}: packshot not found at ${s.packshotPath}`);
  } else if (!CHECK) {
    await sharp(s.packshotPath)
      .resize({ height: PACKSHOT_H, fit: 'inside', withoutEnlargement: true })
      .webp({ quality: 82, alphaQuality: 90, effort: 5 })
      .toFile(dest);
    written++;
  }

  // gameStat.focus is 0 for every SKU by design — CLAIMS_TO_REVIEW.md §5.
  // Assert it here rather than trusting it, because a single non-zero value
  // would turn the mechanic into a prohibited cognition claim.
  if (s.gameStat.focus !== 0) {
    console.error(`✗ ${s.id}: gameStat.focus is ${s.gameStat.focus}, must be 0`);
    process.exit(1);
  }

  records.push({
    id: s.id,
    nameEn: s.nameEn,
    nameCz: s.nameCz ?? null,
    range: s.range,
    phase: s.phase,
    alsoPhase: s.alsoPhase ?? null,
    carbsG: num(s.carbsG),
    sodiumMg: num(s.sodiumMg),
    caffeineMg: num(s.caffeineMg),
    proteinG: num(s.proteinG),
    volumeMl: num(s.volumeMl),
    verified: !!s.verified,
    packshot: existsSync(dest) ? `/${art}` : null,
    stat: {
      glycogen: s.gameStat.glycogen,
      hydration: s.gameStat.hydration,
      bloodSugar: s.gameStat.bloodSugar,
    },
  });
}

function num(v) {
  return typeof v === 'number' && Number.isFinite(v) ? v : null;
}

const header = `/**
 * GENERATED by tools/nutrition/build.mjs from docs/ENERVIT_SKU_MAP.json.
 * Do not edit by hand — edit the SKU map and re-run the tool.
 *
 * Trimmed to what the runtime needs. The provenance notes, source citations and
 * verification flags that make the SKU map trustworthy stay in the document;
 * the game ships the numbers.
 *
 * COMPLIANCE. There is no \`focus\` field on \`stat\` and there must never be
 * one: no product may move the focus stat, directly or indirectly
 * (docs/CLAIMS_TO_REVIEW.md §5). The build tool fails if any SKU declares a
 * non-zero focus effect. Nothing in this file is player-facing copy — see
 * src/nutrition/protocol.ts for why the game states composition only.
 */

export type NutritionPhase = 'before' | 'during' | 'after';

export interface Sku {
  id: string;
  nameEn: string;
  nameCz: string | null;
  range: string;
  phase: NutritionPhase;
  alsoPhase: NutritionPhase | null;
  /** Per single serving, as defined by the SKU map's servingNote. */
  carbsG: number | null;
  sodiumMg: number | null;
  caffeineMg: number | null;
  proteinG: number | null;
  volumeMl: number | null;
  /** True when every headline number was read off a primary source. */
  verified: boolean;
  packshot: string | null;
  /** Game-model deltas. Design starting points, not measurements. */
  stat: { glycogen: number; hydration: number; bloodSugar: number };
}

export const SKUS: readonly Sku[] = `;

writeFileSync(
  OUT_TS,
  header +
    JSON.stringify(records, null, 2) +
    ` as const;

export function skuById(id: string): Sku | undefined {
  return SKUS.find((s) => s.id === id);
}

/** SKUs usable in a phase, including those the map marks as \`alsoPhase\`. */
export function skusForPhase(phase: NutritionPhase): Sku[] {
  return SKUS.filter((s) => s.phase === phase || s.alsoPhase === phase);
}
`,
);

console.log(
  CHECK
    ? `✓ checked ${records.length} SKUs (${missing} packshots missing)`
    : `✓ ${records.length} SKUs → src/data/enervit.ts, ${written} packshots → public/art/enervit/`,
);
