/**
 * GENERATED by tools/nutrition/build.mjs from docs/ENERVIT_SKU_MAP.json.
 * Do not edit by hand — edit the SKU map and re-run the tool.
 *
 * Trimmed to what the runtime needs. The provenance notes, source citations and
 * verification flags that make the SKU map trustworthy stay in the document;
 * the game ships the numbers.
 *
 * COMPLIANCE. There is no `focus` field on `stat` and there must never be
 * one: no product may move the focus stat, directly or indirectly
 * (docs/CLAIMS_TO_REVIEW.md §5). The build tool fails if any SKU declares a
 * non-zero focus effect. Nothing in this file is player-facing copy — see
 * src/nutrition/protocol.ts for why the game states composition only.
 */

export type NutritionPhase = 'before' | 'during' | 'after';

export interface Sku {
  id: string;
  nameEn: string;
  nameCz: string | null;
  range: string;
  phase: NutritionPhase;
  alsoPhase: NutritionPhase | null;
  /** Per single serving, as defined by the SKU map's servingNote. */
  carbsG: number | null;
  sodiumMg: number | null;
  caffeineMg: number | null;
  proteinG: number | null;
  volumeMl: number | null;
  /** True when every headline number was read off a primary source. */
  verified: boolean;
  packshot: string | null;
  /** Game-model deltas. Design starting points, not measurements. */
  stat: { glycogen: number; hydration: number; bloodSugar: number };
}

export const SKUS: readonly Sku[] = [
  {
    "id": "pre-sport-jelly-orange",
    "nameEn": "Pre Sport Jelly Orange",
    "nameCz": "ENERVIT PRE Sport – pomeranč",
    "range": "SPORT",
    "phase": "before",
    "alsoPhase": null,
    "carbsG": 25.6,
    "sodiumMg": 108,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": null,
    "verified": false,
    "packshot": "/art/enervit/pre-sport-jelly-orange.webp",
    "stat": {
      "glycogen": 0.35,
      "hydration": 0,
      "bloodSugar": 0.25
    }
  },
  {
    "id": "pre-sport-jelly-cola-caffeine",
    "nameEn": "Pre Sport Jelly Cola with caffeine",
    "nameCz": "ENERVIT PRE Sport – cola+kofein",
    "range": "SPORT",
    "phase": "before",
    "alsoPhase": null,
    "carbsG": 25.6,
    "sodiumMg": null,
    "caffeineMg": null,
    "proteinG": 0,
    "volumeMl": null,
    "verified": false,
    "packshot": "/art/enervit/pre-sport-jelly-cola-caffeine.webp",
    "stat": {
      "glycogen": 0.35,
      "hydration": 0,
      "bloodSugar": 0.25
    }
  },
  {
    "id": "pre-sport-jelly-cranberry",
    "nameEn": "Pre Sport Jelly Cranberry",
    "nameCz": "ENERVIT PRE Sport – brusinka",
    "range": "SPORT",
    "phase": "before",
    "alsoPhase": null,
    "carbsG": 25.6,
    "sodiumMg": null,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": null,
    "verified": false,
    "packshot": "/art/enervit/pre-sport-jelly-cranberry.webp",
    "stat": {
      "glycogen": 0.35,
      "hydration": 0,
      "bloodSugar": 0.25
    }
  },
  {
    "id": "isotonic-drink-lemon",
    "nameEn": "Isotonic Drink Lemon",
    "nameCz": "ENERVIT Isotonic Drink – citron",
    "range": "SPORT",
    "phase": "during",
    "alsoPhase": "before",
    "carbsG": 25,
    "sodiumMg": 240,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": 500,
    "verified": true,
    "packshot": "/art/enervit/isotonic-drink-lemon.webp",
    "stat": {
      "glycogen": 0.2,
      "hydration": 0.6,
      "bloodSugar": 0.15
    }
  },
  {
    "id": "isotonic-drink-orange",
    "nameEn": "Isotonic Drink Orange",
    "nameCz": "ENERVIT Isotonic Drink – pomeranč",
    "range": "SPORT",
    "phase": "during",
    "alsoPhase": "before",
    "carbsG": 25,
    "sodiumMg": 240,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": 500,
    "verified": false,
    "packshot": "/art/enervit/isotonic-drink-orange.webp",
    "stat": {
      "glycogen": 0.2,
      "hydration": 0.6,
      "bloodSugar": 0.15
    }
  },
  {
    "id": "gel-citrus",
    "nameEn": "Enervit Gel Citrus",
    "nameCz": "ENERVIT Gel",
    "range": "SPORT",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 20,
    "sodiumMg": 10,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": 25,
    "verified": false,
    "packshot": "/art/enervit/gel-citrus.webp",
    "stat": {
      "glycogen": 0.25,
      "hydration": -0.05,
      "bloodSugar": 0.55
    }
  },
  {
    "id": "gel-raspberry-caffeine",
    "nameEn": "Enervit Gel Raspberry with caffeine",
    "nameCz": "ENERVIT Gel",
    "range": "SPORT",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 20,
    "sodiumMg": 10,
    "caffeineMg": 20,
    "proteinG": 0,
    "volumeMl": 25,
    "verified": true,
    "packshot": "/art/enervit/gel-raspberry-caffeine.webp",
    "stat": {
      "glycogen": 0.25,
      "hydration": -0.05,
      "bloodSugar": 0.55
    }
  },
  {
    "id": "gel-cola",
    "nameEn": "Enervit Gel Cola",
    "nameCz": "ENERVIT Gel",
    "range": "SPORT",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 20,
    "sodiumMg": 10,
    "caffeineMg": null,
    "proteinG": 0,
    "volumeMl": 25,
    "verified": false,
    "packshot": "/art/enervit/gel-cola.webp",
    "stat": {
      "glycogen": 0.25,
      "hydration": -0.05,
      "bloodSugar": 0.55
    }
  },
  {
    "id": "liquid-gel-citrus",
    "nameEn": "Liquid Gel Citrus",
    "nameCz": "ENERVIT Liquid Gel Competition s kofeinem",
    "range": "SPORT",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 30,
    "sodiumMg": null,
    "caffeineMg": null,
    "proteinG": 0,
    "volumeMl": 60,
    "verified": true,
    "packshot": "/art/enervit/liquid-gel-citrus.webp",
    "stat": {
      "glycogen": 0.4,
      "hydration": 0.05,
      "bloodSugar": 0.45
    }
  },
  {
    "id": "liquid-gel-orange",
    "nameEn": "Liquid Gel Orange",
    "nameCz": "ENERVIT Liquid Gel",
    "range": "SPORT",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 30,
    "sodiumMg": null,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": 60,
    "verified": true,
    "packshot": "/art/enervit/liquid-gel-orange.webp",
    "stat": {
      "glycogen": 0.4,
      "hydration": 0.05,
      "bloodSugar": 0.45
    }
  },
  {
    "id": "isotonic-gel-grapefruit",
    "nameEn": "Isotonic Gel Grapefruit",
    "nameCz": "ENERVIT Isotonic Gel",
    "range": "SPORT",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 20,
    "sodiumMg": null,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": null,
    "verified": false,
    "packshot": "/art/enervit/isotonic-gel-grapefruit.webp",
    "stat": {
      "glycogen": 0.25,
      "hydration": 0.2,
      "bloodSugar": 0.35
    }
  },
  {
    "id": "isotonic-gel-lemon-caffeine",
    "nameEn": "Isotonic Gel Lemon with caffeine",
    "nameCz": "ENERVIT Isotonic Gel s kofeinem",
    "range": "SPORT",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 20,
    "sodiumMg": null,
    "caffeineMg": null,
    "proteinG": 0,
    "volumeMl": null,
    "verified": false,
    "packshot": "/art/enervit/isotonic-gel-lemon-caffeine.webp",
    "stat": {
      "glycogen": 0.25,
      "hydration": 0.2,
      "bloodSugar": 0.35
    }
  },
  {
    "id": "competition-bar-orange",
    "nameEn": "Competition Bar Orange",
    "nameCz": "ENERVIT Competition Bar",
    "range": "SPORT",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 20,
    "sodiumMg": null,
    "caffeineMg": 0,
    "proteinG": null,
    "volumeMl": null,
    "verified": false,
    "packshot": "/art/enervit/competition-bar-orange.webp",
    "stat": {
      "glycogen": 0.35,
      "hydration": -0.1,
      "bloodSugar": 0.3
    }
  },
  {
    "id": "carbo-gel-orange",
    "nameEn": "Carbo Gel Orange C2:1 PRO",
    "nameCz": "ENERVIT Carbo Gel C2:1",
    "range": "C2_1",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 40,
    "sodiumMg": null,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": 60,
    "verified": false,
    "packshot": "/art/enervit/carbo-gel-orange.webp",
    "stat": {
      "glycogen": 0.5,
      "hydration": -0.1,
      "bloodSugar": 0.6
    }
  },
  {
    "id": "carbo-gel-cola-caffeine",
    "nameEn": "Carbo Gel Cola with caffeine C2:1 PRO",
    "nameCz": "ENERVIT Carbo Gel C2:1 – cola+kofein",
    "range": "C2_1",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 40,
    "sodiumMg": 0,
    "caffeineMg": 100,
    "proteinG": 0,
    "volumeMl": 60,
    "verified": true,
    "packshot": "/art/enervit/carbo-gel-cola-caffeine.webp",
    "stat": {
      "glycogen": 0.5,
      "hydration": -0.1,
      "bloodSugar": 0.6
    }
  },
  {
    "id": "carbo-gel-lemon-sodium",
    "nameEn": "Carbo Gel Lemon Sodium C2:1 PRO",
    "nameCz": "ENERVIT Carbo Gel C2:1 – se sodíkem",
    "range": "C2_1",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 40,
    "sodiumMg": 200,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": 60,
    "verified": false,
    "packshot": "/art/enervit/carbo-gel-lemon-sodium.webp",
    "stat": {
      "glycogen": 0.5,
      "hydration": 0.05,
      "bloodSugar": 0.6
    }
  },
  {
    "id": "carbo-gel-lime",
    "nameEn": "Carbo Gel Lime C2:1 PRO",
    "nameCz": "ENERVIT Carbo Gel C2:1 – limetka",
    "range": "C2_1",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 40,
    "sodiumMg": null,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": 60,
    "verified": false,
    "packshot": "/art/enervit/carbo-gel-lime.webp",
    "stat": {
      "glycogen": 0.5,
      "hydration": -0.1,
      "bloodSugar": 0.6
    }
  },
  {
    "id": "carbo-gel-mango",
    "nameEn": "Carbo Gel Mango C2:1 PRO",
    "nameCz": "ENERVIT Carbo Gel C2:1",
    "range": "C2_1",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 40,
    "sodiumMg": null,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": 60,
    "verified": false,
    "packshot": "/art/enervit/carbo-gel-mango.webp",
    "stat": {
      "glycogen": 0.5,
      "hydration": -0.1,
      "bloodSugar": 0.6
    }
  },
  {
    "id": "carbo-jelly-tropical",
    "nameEn": "Carbo Jelly Tropical Fruits C2:1 PRO",
    "nameCz": "ENERVIT Carbo Jelly C2:1 – tropické ovoce",
    "range": "C2_1",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 30,
    "sodiumMg": 52,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": null,
    "verified": true,
    "packshot": "/art/enervit/carbo-jelly-tropical.webp",
    "stat": {
      "glycogen": 0.3,
      "hydration": -0.05,
      "bloodSugar": 0.5
    }
  },
  {
    "id": "carbo-chews-orange",
    "nameEn": "Carbo Chews Orange C2:1 PRO",
    "nameCz": "ENERVIT Carbo Chews C2:1 – pomeranč",
    "range": "C2_1",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 30,
    "sodiumMg": 0,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": null,
    "verified": true,
    "packshot": "/art/enervit/carbo-chews-orange.webp",
    "stat": {
      "glycogen": 0.3,
      "hydration": -0.05,
      "bloodSugar": 0.4
    }
  },
  {
    "id": "carbo-bar-peanut",
    "nameEn": "Carbo Bar Salty Peanut Butter C2:1 PRO",
    "nameCz": null,
    "range": "C2_1",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 33,
    "sodiumMg": 204,
    "caffeineMg": 0,
    "proteinG": 1.6,
    "volumeMl": null,
    "verified": true,
    "packshot": "/art/enervit/carbo-bar-peanut.webp",
    "stat": {
      "glycogen": 0.4,
      "hydration": -0.05,
      "bloodSugar": 0.25
    }
  },
  {
    "id": "carbo-bar-brownie",
    "nameEn": "Carbo Bar Brownie C2:1 PRO",
    "nameCz": "ENERVIT Carbo Bar C2:1 – brownie",
    "range": "C2_1",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 33.3,
    "sodiumMg": 7.2,
    "caffeineMg": 0,
    "proteinG": 2,
    "volumeMl": null,
    "verified": true,
    "packshot": "/art/enervit/carbo-bar-brownie.webp",
    "stat": {
      "glycogen": 0.4,
      "hydration": -0.05,
      "bloodSugar": 0.25
    }
  },
  {
    "id": "carbo-bar-no-flavour",
    "nameEn": "Carbo Bar No Flavour C2:1 PRO",
    "nameCz": null,
    "range": "C2_1",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 33.3,
    "sodiumMg": 7.2,
    "caffeineMg": 0,
    "proteinG": 2,
    "volumeMl": null,
    "verified": true,
    "packshot": "/art/enervit/carbo-bar-no-flavour.webp",
    "stat": {
      "glycogen": 0.4,
      "hydration": -0.05,
      "bloodSugar": 0.25
    }
  },
  {
    "id": "isocarb",
    "nameEn": "Isocarb C2:1 PRO",
    "nameCz": "ENERVIT Isocarb C2:1",
    "range": "C2_1",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 60,
    "sodiumMg": 240,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": 500,
    "verified": true,
    "packshot": "/art/enervit/isocarb.webp",
    "stat": {
      "glycogen": 0.6,
      "hydration": 0.25,
      "bloodSugar": 0.4
    }
  },
  {
    "id": "isocarb-sachet-mild-lemon",
    "nameEn": "Isocarb C2:1 PRO sachets, Mild Lemon",
    "nameCz": null,
    "range": "C2_1",
    "phase": "during",
    "alsoPhase": null,
    "carbsG": 60,
    "sodiumMg": 240,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": 500,
    "verified": false,
    "packshot": "/art/enervit/isocarb-sachet-mild-lemon.webp",
    "stat": {
      "glycogen": 0.6,
      "hydration": 0.25,
      "bloodSugar": 0.4
    }
  },
  {
    "id": "salt-caps",
    "nameEn": "Salt Caps",
    "nameCz": "ENERVIT Salt Caps",
    "range": "SPORT",
    "phase": "during",
    "alsoPhase": "before",
    "carbsG": 0,
    "sodiumMg": 300,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": null,
    "verified": false,
    "packshot": "/art/enervit/salt-caps.webp",
    "stat": {
      "glycogen": 0,
      "hydration": 0.3,
      "bloodSugar": 0
    }
  },
  {
    "id": "r2-recovery-drink",
    "nameEn": "R2 Recovery Drink",
    "nameCz": "ENERVIT R2 Recovery Drink",
    "range": "SPORT",
    "phase": "after",
    "alsoPhase": null,
    "carbsG": 41,
    "sodiumMg": 68,
    "caffeineMg": 0,
    "proteinG": 4.4,
    "volumeMl": 350,
    "verified": true,
    "packshot": "/art/enervit/r2-recovery-drink.webp",
    "stat": {
      "glycogen": 0.7,
      "hydration": 0.35,
      "bloodSugar": 0.3
    }
  },
  {
    "id": "whey-protein-cocoa",
    "nameEn": "100% Whey Protein Cocoa",
    "nameCz": "ENERVIT 100% Whey Protein",
    "range": "SPORT",
    "phase": "after",
    "alsoPhase": null,
    "carbsG": null,
    "sodiumMg": null,
    "caffeineMg": 0,
    "proteinG": null,
    "volumeMl": null,
    "verified": false,
    "packshot": "/art/enervit/whey-protein-cocoa.webp",
    "stat": {
      "glycogen": 0.1,
      "hydration": 0.1,
      "bloodSugar": 0.05
    }
  },
  {
    "id": "magic-cherry",
    "nameEn": "After Sport Magic Cherry",
    "nameCz": "ENERVIT Magic Cherry",
    "range": "SPORT",
    "phase": "after",
    "alsoPhase": null,
    "carbsG": null,
    "sodiumMg": null,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": null,
    "verified": true,
    "packshot": "/art/enervit/magic-cherry.webp",
    "stat": {
      "glycogen": 0,
      "hydration": 0,
      "bloodSugar": 0
    }
  },
  {
    "id": "magnesium-lemon",
    "nameEn": "Magnesium Lemon",
    "nameCz": "ENERVIT Magnesium Sport",
    "range": "SPORT",
    "phase": "after",
    "alsoPhase": null,
    "carbsG": null,
    "sodiumMg": null,
    "caffeineMg": 0,
    "proteinG": 0,
    "volumeMl": null,
    "verified": false,
    "packshot": "/art/enervit/magnesium-lemon.webp",
    "stat": {
      "glycogen": 0,
      "hydration": 0.15,
      "bloodSugar": 0
    }
  }
] as const;

export function skuById(id: string): Sku | undefined {
  return SKUS.find((s) => s.id === id);
}

/** SKUs usable in a phase, including those the map marks as `alsoPhase`. */
export function skusForPhase(phase: NutritionPhase): Sku[] {
  return SKUS.filter((s) => s.phase === phase || s.alsoPhase === phase);
}
